### ISSUE TITLE
approx 98.3% of build time (~2min for me) is caused by Tileset Installer.event

### ISSUE THREAD

**Issue by StanHash** [jfarr095/Basefile#1]
With `Tileset Installer.event` included:
```
real    1m57.640s
user    1m54.967s
sys     0m2.343s
```

Without `Tileset Installer.event` included:
```
real    0m2.172s
user    0m1.923s
sys     0m0.268s
```

I feel like there's probably a bit too much `#incext` involved.

(This is, of course, using outputs from no-PFinder!c2ea and text-process-classic, which do not add any extra tool calls)

(Note: using timing ColorzCore later reveals that this is mostly caused by Png2Dmp invocations (1min17 out of 1min20 for that particular run))

**Comment by jfarr095** [comment]
Thanks for the report.
I've unincluded tilesets for now. A more elegant solution for inserting them is pending.
In the meantime, users can copy any of the extra tilesets they were using to their _UserData folders.
